// Generated by CoffeeScript 1.6.2
(function() {
  var Dragging, SelectionRect, Square, SquareGroups, doStuff, log, squares,
    __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  log = function() {
    var args;

    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if ((typeof console !== "undefined" && console !== null ? console.log : void 0) != null) {
      return console.log.apply(console, args);
    }
  };

  $(function() {
    return doStuff();
  });

  SquareGroups = (function() {
    function SquareGroups() {
      this.squares = [];
    }

    SquareGroups.prototype.Push = function(s) {
      if (!s) {
        return;
      }
      log('pushing ', s.div[0]);
      return this.squares.push(s);
    };

    SquareGroups.prototype.ProcessColliding = function(s) {
      var i, _i, _len, _ref, _results;

      _ref = this.squares;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        _results.push((function(i) {
          var j, r, _j, _len1, _results1;

          if (i.IsColliding(s) && i.Masking) {
            log('is colliding', s.div[0], s);
            r = i.SplitWith(s);
            log(r);
            if (j) {
              _results1 = [];
              for (_j = 0, _len1 = r.length; _j < _len1; _j++) {
                j = r[_j];
                _results1.push(log('j: ', j.div[0]));
              }
              return _results1;
            }
          }
        })(i));
      }
      return _results;
    };

    return SquareGroups;

  })();

  squares = new SquareGroups;

  Dragging = false;

  Square = (function() {
    function Square(x, y, w, h, Masking) {
      this.x = x;
      this.y = y;
      this.w = w;
      this.h = h;
      this.Masking = Masking != null ? Masking : true;
      this.StopDragging = __bind(this.StopDragging, this);
      this.WhileDragging = __bind(this.WhileDragging, this);
      this.Destroy = __bind(this.Destroy, this);
      this.updateIntersections = __bind(this.updateIntersections, this);
      this.rectSplits = __bind(this.rectSplits, this);
      this.intersectionPoints = __bind(this.intersectionPoints, this);
      this.intersectingRect = __bind(this.intersectingRect, this);
      this.updateDiv = __bind(this.updateDiv, this);
      this.hookMouseMove = __bind(this.hookMouseMove, this);
      if (this.w === 0 || this.h === 0) {
        return null;
      }
      this.div = $('<div class="mask">');
      this.splits = {};
      this.updateDiv();
      $('body').append(this.div);
      this;
    }

    Square.prototype.hookMouseMove = function() {
      return this.div.mousemove(this.WhileDragging);
    };

    Square.prototype.updateDiv = function() {
      return this.div.css({
        top: this.y + 'px',
        left: this.x + 'px',
        width: this.w + 'px',
        height: this.h + 'px'
      });
    };

    Square.prototype.Changing = function() {
      return [false, false, true, true];
    };

    Square.prototype.IsColliding = function(s) {
      return !(this.x + this.w <= s.x || this.x >= s.x + s.w || this.y + this.h <= s.y || this.y >= s.y + s.h);
    };

    Square.prototype.intersectingRect = function(s) {
      var h, rbx, rby, w, x, y, _ref, _ref1;

      _ref = [s.x, s.y, s.w, s.h], x = _ref[0], y = _ref[1], w = _ref[2], h = _ref[3];
      _ref1 = [x + w, y + h], rbx = _ref1[0], rby = _ref1[1];
      x = x < this.x ? this.x : x;
      y = y < this.y ? this.y : y;
      w = rbx > this.x + this.w ? this.x + this.w - x : rbx - x;
      h = rby > this.y + this.h ? this.y + this.h - y : rby - y;
      return [x, y, w, h];
    };

    Square.prototype.intersectionPoints = function(x, y, w, h) {
      return {
        fcs: this.x,
        fcw: x - this.x,
        mcs: x,
        mcw: w,
        lcs: x + w,
        lcw: this.x + this.w - (x + w),
        frs: this.y,
        frh: y - this.y,
        mrs: y,
        mrh: h,
        lrs: y + h,
        lrh: this.y + this.h - (y + h)
      };
    };

    Square.prototype.rectSplits = function(p) {
      return {
        nw: [p.fcs, p.frs, p.fcw, p.frh],
        w: [p.fcs, p.mrs, p.fcw, p.mrh],
        sw: [p.fcs, p.lrs, p.fcw, p.lrh],
        n: [p.mcs, p.frs, p.mcw, p.frh],
        s: [p.mcs, p.lrs, p.mcw, p.lrh],
        ne: [p.lcs, p.frs, p.lcw, p.frh],
        e: [p.lcs, p.mrs, p.lcw, p.mrh],
        se: [p.lcs, p.lrs, p.lcw, p.lrh]
      };
    };

    Square.prototype.updateIntersections = function(s) {
      var d, h, splits, updateSquare, v, w, x, y, _ref, _results,
        _this = this;

      _ref = this.intersectingRect(s), x = _ref[0], y = _ref[1], w = _ref[2], h = _ref[3];
      if (s.x !== x || s.y !== y || s.w !== w || s.h !== h) {
        log(' ----- collision ');
        squares.ProcessColliding(s);
      }
      splits = this.rectSplits(this.intersectionPoints(x, y, w, h));
      updateSquare = function(d, v) {
        if (!_this.splits[d]) {
          return;
        }
        _this.splits[d].x = v[0];
        _this.splits[d].y = v[1];
        _this.splits[d].w = v[2];
        _this.splits[d].h = v[3];
        return _this.splits[d].updateDiv();
      };
      _results = [];
      for (d in splits) {
        v = splits[d];
        _results.push(updateSquare(d, v));
      }
      return _results;
    };

    Square.prototype.SplitWith = function(s) {
      var d, h, newSquare, splits, v, w, x, y, _ref, _ref1;

      _ref = this.intersectingRect(s), x = _ref[0], y = _ref[1], w = _ref[2], h = _ref[3];
      log(' the selection square', x, y, w, h);
      newSquare = function(xx, yy, ww, hh) {
        if (x === xx && y === yy && w === ww && h === hh) {
          return null;
        }
        if (hh === 0 || ww === 0) {
          return null;
        }
        return new Square(xx, yy, ww, hh);
      };
      this.div.css('display', 'none');
      log('splitting', this, '  with ', s);
      this.Masking = false;
      splits = this.rectSplits(this.intersectionPoints(x, y, w, h));
      for (d in splits) {
        v = splits[d];
        this.splits[d] = newSquare.apply(null, v);
      }
      _ref1 = this.splits;
      for (d in _ref1) {
        v = _ref1[d];
        log(d, (v ? v.div[0] : void 0));
      }
      s.rects.push(this);
      return this;
    };

    Square.prototype.Destroy = function() {
      return this.div.remove();
    };

    Square.prototype.WhileDragging = function(e) {
      if (!Dragging) {
        return;
      }
      if (!this.dragSquare) {
        this.dragSquare = new SelectionRect(e.pageX, e.pageY, 1, 1);
        log('started dragging', this.dragSquare);
        this.SplitWith(this.dragSquare);
      }
      this.dragSquare.WhileDragging(e);
      return this.updateIntersections(this.dragSquare);
    };

    Square.prototype.StopDragging = function(e) {
      var d, n, _ref, _results;

      log('stopping, and pushing all squares', this.splits);
      _ref = this.splits;
      _results = [];
      for (d in _ref) {
        n = _ref[d];
        if (n && n.w !== 0 && n.h !== 0) {
          _results.push(squares.Push(n));
        } else {
          _results.push(n != null ? n.Destroy() : void 0);
        }
      }
      return _results;
    };

    return Square;

  })();

  SelectionRect = (function() {
    function SelectionRect(x, y, w, h) {
      this.x = x;
      this.y = y;
      this.w = w;
      this.h = h;
      this.StopDragging = __bind(this.StopDragging, this);
      this.WhileDragging = __bind(this.WhileDragging, this);
      this.updateDiv = __bind(this.updateDiv, this);
      this.div = $('<div class="sel-rect">');
      this.rects = [];
      $('body').append(this.div);
      this;
    }

    SelectionRect.prototype.updateDiv = function() {
      return this.div.css({
        top: this.y + 'px',
        left: this.x + 'px',
        width: this.w + 'px',
        height: this.h + 'px'
      });
    };

    SelectionRect.prototype.Changing = function() {
      return [false, false, true, true];
    };

    SelectionRect.prototype.WhileDragging = function(e) {
      var r, _i, _len, _ref;

      this.w = e.pageX - this.x;
      this.h = e.pageY - this.y;
      _ref = this.rects;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        r = _ref[_i];
        r.updateIntersections(this);
      }
      return this.updateDiv();
    };

    SelectionRect.prototype.StopDragging = function(e) {
      var r, _i, _len, _ref, _results;

      log('selectionrect drag stop');
      _ref = this.rects;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        r = _ref[_i];
        _results.push(r.StopDragging(e));
      }
      return _results;
    };

    return SelectionRect;

  })();

  doStuff = function() {
    var $b, $d, Sels, h, s, sel, w, _ref;

    _ref = [window.document.width, window.document.height], w = _ref[0], h = _ref[1];
    s = new Square(0, 0, w, h);
    $b = $('body');
    log('dostuff', s.div.attr('id', 'fullmask'));
    $b.append(s.div);
    squares.Push(s);
    $d = $('body');
    Sels = [];
    sel = null;
    return $d.mousedown(function(e) {
      log('start dragging %O', squares.squares);
      Dragging = true;
      sel = new SelectionRect(e.pageX, e.pageY, 1, 1);
      squares.ProcessColliding(sel);
      $d.mousemove(sel.WhileDragging);
      return $d.mouseup(function(e) {
        log('stopping drag');
        sel.StopDragging(e);
        Dragging = false;
        $d.off('mousemove');
        return $d.off('mouseup');
      });
    });
  };

}).call(this);
